apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-chart.fullname" . }}
  labels:
    app: {{ include "keycloak-chart.name" . }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: {{ include "keycloak-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "keycloak-chart.name" . }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          env:
            - name: KC_DB_URL_HOST
              value: "{{ .Values.postgres.service.name }}"
          {{- range $key, $value := .Values.keycloak.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
          args:
          {{- range .Values.keycloak.args }}
            - {{ . }}
          {{- end }}
          volumeMounts:
          {{- range .Values.keycloak.volumeMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
          {{- end }}
      volumes:
      {{- range .Values.keycloak.volumes }}
        - name: {{ .name }}
          {{- if .emptyDir }}
          emptyDir: {}
          {{- end }}
      {{- end }}

