---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:25.0.1
        env:
        - name: KC_DB
          value: postgres
            #- name: KC_DB_URL_HOST
            #value: postgres-service
            #- name: KC_DB_URL_PORT
            #value: "5432"
        - name: KC_DB_URL_DATABASE
          value: ps_db
        - name: KC_DB_USERNAME
          value: ps_user
        - name: KC_DB_PASSWORD
          value: SecurePassword
        
         # Admin user configurations  
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        ports:
        - containerPort: 8080
        - containerPort: 8443
        args:
        - start-dev
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/standalone/data
          name: keycloak-data
      volumes:
      - name: keycloak-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
